version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: computerwinkel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    build:
      dockerfile: ./.docker/phpmyadmin/Dockerfile
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
volumes:
  dbdata:



